Fix env lookup when .env.VAR is undefined
When .env.MEMORY_INTENSIVE_CLUSTER_SIZING is undefined, helm template
kubecost ./cost-analyzer would fail with:

Error: template: cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml:589:15: executing "cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml" at <eq .Values.kubecostAggregator.env.MEMORY_INTENSIVE_CLUSTER_SIZING "enabled">: error calling eq: incompatible types for comparison

This is because Helm won't let us compare nil with string. Switching to
the default operator fixes this

Signed-off-by: Michael Dresser <michaelmdresser@gmail.com>