Fix indentation of network-costs requests/limits
Helm install with --set networkCosts.enabled=true was failing:

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(DaemonSet.spec.template.spec.containers[0]): unknown field "limits" in io.k8s.api.core.v1.Container, ValidationError(DaemonSet.spec.template.spec.containers[0]): unknown field "requests" in io.k8s.api.core.v1.Container]

This was caused by an incorrect indent on the resources block.

→ helm template kubecost . -s templates/cost-analyzer-network-costs-template.yaml --set networkCosts.enabled=true | grep -A 5 -B 2 'resources'

Before this change:
        image: gcr.io/kubecost1/kubecost-network-costs:v16.3
        imagePullPolicy: Always
        resources:
        limits:
          cpu: 500m
        requests:
          cpu: 50m
          memory: 20Mi

After this change:
        image: gcr.io/kubecost1/kubecost-network-costs:v16.3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 50m
            memory: 20Mi

Also after the change, the install works.

Signed-off-by: Michael Dresser <michaelmdresser@gmail.com>