Fix for breaking changes in kubernetes API v1.16
see https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

"in 1.16 if you submit a Deployment to the API server and specify extensions/v1beta1 as the API group it will be rejected with:
error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"