Fix failed install/template with no values on older versions of Helm3 (#3175) (#3176)
* Fix fqdn when .api is undefined

Helm doesn't appear to have short-circuiting on the and operator, meaning
the (and .api .api.fqdn) check doesn't work. This fancy parentheses thing
does what we actually want.

Before this, helm template kubecost ./cost-analyzer fails with

Error: template: cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml:57:52: executing "cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml" at <.Values.kubecostFrontend.api.fqdn>: nil pointer evaluating interface {}.fqdn



* Fix env lookup when .env.VAR is undefined

When .env.MEMORY_INTENSIVE_CLUSTER_SIZING is undefined, helm template
kubecost ./cost-analyzer would fail with:

Error: template: cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml:589:15: executing "cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml" at <eq .Values.kubecostAggregator.env.MEMORY_INTENSIVE_CLUSTER_SIZING "enabled">: error calling eq: incompatible types for comparison

This is because Helm won't let us compare nil with string. Switching to
the default operator fixes this



---------

Signed-off-by: Michael Dresser <michaelmdresser@gmail.com>
Co-authored-by: Michael Dresser <michaelmdresser@gmail.com>