Don't use eq to default a possibly-nil value
kubecostModel.etlCloudAsset is nil by default. Before this change,
running helm template would give the following error:

Error: template: cost-analyzer/templates/cost-analyzer-deployment-template.yaml:533:19: executing "cost-analyzer/templates/cost-analyzer-deployment-template.yaml" at <eq .Values.kubecostModel.etlCloudAsset false>: error calling eq: incompatible types for comparison

After the change, the error is gone. Testing of the logic:

→ helm template ./cost-analyzer | grep -A 1 -i ETL_CLOUD
            - name : ETL_CLOUD_USAGE_ENABLED
              value: "false"

→ helm template ./cost-analyzer --set kubecostModel.etlCloudAsset=true | grep -A 1 -i ETL_CLOUD
            - name : ETL_CLOUD_USAGE_ENABLED
              value: "true"